
GET http://localhost:3000/projeto

###

POST http://localhost:3000/projeto  
content-type: application/json

{
   
    "titulo": "Loja",
    "imagemUrl": "qeqerqre23214",
    "descricao": "Projeto feito para Loja",
    "tecnologiasImg": "nextjs, nestjs, postgresql",
    "linkCodigo": "23414"
}

###

DELETE http://localhost:3000/projeto/2
